### ISSUE TITLE
Cannot pull wikitext for non-Wikipedia wiki

### ISSUE THREAD

**Issue by TheDocTrier** [Frederisk/Wikitext-VSCode-Extension#11]
Everything seems to be working fine when using English Wikipedia. However, when I change the host to `en.wikifur.com` and attempt to pull a page, all I get is an error notification which says `undefined! undefined`. It's too cryptic for me to understand, so I thought I should report it here.

**Comment by Frederisk** [comment]
Are there any other prompt messages when using View Page, Post and other functions?

I need more information to determine the problem.🤔

**Comment by TheDocTrier** [comment]
View the page seems to work fine. Trying to post yields the error messages:

```
Command 'Wikitext: Post your edit to the website' resulted in an error (badtoken: Invalid token)
```
and
```
Error
```

**Comment by siddharthvp** [comment]
That site uses a really old version of MediaWiki: [1.23.16](https://en.wikifur.com/w/api.php?action=query&meta=siteinfo&format=xml)

**Comment by Frederisk** [comment]
@siddharthvp Yes, I also noticed this. Maybe this is the reason for the error: a different API return or Token category.

However, I am very busy recently. In order to test this old version of mediawiki, I need to go to the website to register an account or find an old version to build a test environment.

I have to wait until I have time to spend some time to resolve it.
