### ISSUE TITLE
Bug: preview doesn't work

### ISSUE THREAD

**Issue by rinrab** [Frederisk/Wikitext-VSCode-Extension#86]
![bug](https://github.com/Frederisk/Wikitext-Extension-Gadget/assets/64201197/75cd3d1d-31ff-4983-8f1c-f9c2e7493b62)

**Comment by Frederisk** [comment]
Wrong location, this is a problem belonging to Wikitext Extension.

**Comment by Frederisk** [comment]
In addition, I meed more information, such as VSCode version, and Extension version.

At the same time, you can try to update/reinstall this Extension, or disable any other Extension as well.

**Comment by rinrab** [comment]
I'm currently using VS Code version 1.83.1. After updating VS Code to version 1.84.0 and reinstalling the extension, I'm still facing issues with it not working. Interestingly, the extension does work in a sandbox environment.

**Comment by Frederisk** [comment]
Well, based on your statement and my testing, I'm more inclined to think this is due to a problem with your other environment settings.

I also noticed that nothing happened after pressing the button. If there are no problems with other functions of this extension, it means that some of the following assertions may have failed.

https://github.com/Frederisk/Wikitext-VSCode-Extension/blob/8d4f27705696abe6eedb6da490598e0691ab905b/src/export_command/wikimedia_function/view.ts#L60-L68

I needed to go into debug mode and set breakpoints to find the problem, but unfortunately I couldn't reproduce the issue.

**Comment by rinrab** [comment]
I entered the hostname in the settings, and it's working! Please make the setup process easier, and in that code config may be null or undefined.

**Comment by Frederisk** [comment]
> Please make the setup process easier, and in that code config may be null or undefined.

This may sound a little strange, but in the code, I have set up a warning to the user when the host is empty. Maybe you accidentally typed a space or similar character at that time?

Anyway, I will consider doing more additional checks on this in the future.
